''
'' Silver theme - mostly grays
''
'' Author: Brett Schwarz
'' Copyright (c) 2019 by Brett Schwarz

!$THEME = "metal"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

skinparam backgroundColor $BGCOLOR

!$WHITE = "#fdfdfd"
!$GRAY_DARK = "#4d4d4d"
!$GRAY = "#737373"
!$LIGHT = "#f2f2f2"
!$DARK = "#4d4d4d"

!$SILVER = "#c0c0c0"
!$COPPER = "#B87333c"
!$STEELBLUE = "#4682b4"
!$LIGHTSTEELBLUE = "#B0C4DE" 
!$LIGHTSTEELBLUE_DARK = "#8d9db2" 
!$LIGHTSTEELBLUE_LIGHT = "#c0d0e5" 
!$ALUMINUM = "#c9ced0"
!$ALUMINUM_DARK = "#a1a5a6"
!$ALUMINUM_LIGHT = "#d4d8d9"
!$BRONZE = "#CD7F32" 
!$BRONZE_DARK = "#a46628" 
!$BRONZE_LIGHT = "#d7995b" 
!$GOLD = "#FFD700"
!$PLATINUM = "#E5E4E2"
!$RUST = "#B7410E"



'' *_LIGHT = tint (lighter) of the main color of 80%
''          where TINT is calculated by clr + (255-clr) * tint_factor
'' *_DARK = shade (darker) of the main color of 80%
''          and SHADE is calculated by clr * (1 - shade_factor)
''
!$FGCOLOR = $DARK
!$PRIMARY = $PLATINUM
!$PRIMARY_LIGHT = "#eae9e8"
!$PRIMARY_DARK = "#b7b6b5"
!$PRIMARY_TEXT = $STEELBLUE
!$SECONDARY = $SILVER
!$SECONDARY_LIGHT = "#cdcdcd"
!$SECONDARY_DARK = "#9a9a9a"
!$SECONDARY_TEXT = $WHITE
!$INFO = $STEELBLUE
!$INFO_LIGHT = "#5c85ad"
!$INFO_DARK = "#29527a"
!$INFO_TEXT = $WHITE
!$SUCCESS = "#339933"
!$SUCCESS_LIGHT = "#5cad5c"
!$SUCCESS_DARK = "#297a29"
!$SUCCESS_TEXT = $WHITE
!$WARNING = $GOLD
!$WARNING_LIGHT = "#ffdf33"
!$WARNING_DARK = "#ccac00"
!$WARNING_TEXT = $WHITE
!$DANGER = $RUST
!$DANGER_LIGHT = "#c5673e"
!$DANGER_DARK = "#92340b"
!$DANGER_TEXT = $WHITE

!function $success($msg)
  <font color=$SUCCESS><b>$msg
!endfunction

!function $failure($msg)
  <font color=$DANGER><b>$msg
!endfunction

!function $warning($msg)
  <font color=$WARNING><b>$msg
!endfunction

''
'' Global Default Values
''
skinparam defaultFontName        "Verdana"
skinparam defaultFontSize        12
skinparam dpi                    100
skinparam shadowing              false
skinparam roundcorner            15
skinparam ParticipantPadding     30
skinparam BoxPadding             30
skinparam Padding                8
skinparam ArrowColor             $GRAY
skinparam stereotype {
    CBackgroundColor $SECONDARY_LIGHT
    CBorderColor $SECONDARY_DARK
    ABackgroundColor $SUCCESS_LIGHT
    ABorderColor $SUCCESS_DARK
    IBackgroundColor $DANGER_LIGHT
    IBorderColor $DANGER_DARK
    EBackgroundColor $WARNING_LIGHT
    EBorderColor $WARNING_DARK
    NBackgroundColor $INFO_LIGHT
    NBorderColor $INFO_DARK
}
skinparam title {
	FontColor	                 $WHITE
	BorderColor	                 $SECONDARY_DARK
	FontSize	    	         20
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              $SECONDARY_LIGHT-$SECONDARY_DARK
}


skinparam legend {
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY
	BorderColor $SECONDARY_DARK
	FontColor $PRIMARY_TEXT
}

!startsub activity
skinparam activity {
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY_DARK
	BackgroundColor $PRIMARY-$PRIMARY_DARK
	BarColor $BRONZE
	StartColor $INFO
	EndColor $INFO
	''
	DiamondBackgroundColor $SECONDARY-$SECONDARY_DARK
  	DiamondBorderColor $SECONDARY_DARK
	DiamondFontColor $SECONDARY_TEXT
}
!endsub

!startsub sequence
skinparam sequence {
	BorderColor $PRIMARY
	' For some reason sequence title font color does not pick up from global
	TitleFontColor $WHITE
	BackgroundColor $BGCOLOR
	StartColor $PRIMARY
	EndColor $PRIMARY
	''
    ParticipantBackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
    ParticipantBorderColor $PRIMARY
	ParticipantBorderThickness 0
	ParticipantFontColor $PRIMARY_TEXT
	''
	ActorBackgroundColor $BGCOLOR
    ActorBorderColor $PRIMARY_DARK
	ActorFontColor $PRIMARY
	''
	ArrowThickness 3
	ArrowColor $PRIMARY
	ArrowFontColor $FGCOLOR
	''
	BoxBackgroundColor $LIGHT
	BoxBorderColor $GRAY
	BoxFontColor $DARK
	''
	LifeLineBorderColor $SECONDARY_DARK
	LifeLineBorderThickness 3
	LifeLineBackgroundColor $SECONDARY_LIGHT-$SECONDARY_DARK
	''
	GroupBorderColor $GRAY
	GroupFontColor $DARK
	GroupHeaderFontColor $INFO
	''
	DividerBackgroundColor $WHITE-$LIGHT
    DividerBorderColor $GRAY
    DividerBorderThickness 2
    DividerFontColor $DARK
	''
	ReferenceBackgroundColor $BGCOLOR
	ReferenceBorderColor $GRAY
	ReferenceFontColor $DARK
	ReferenceHeaderFontColor $INFO
}
!endsub

!startsub partition
skinparam partition {
	BorderColor $PRIMARY
	FontColor $PRIMARY_DARK
	BackgroundColor $BGCOLOR
}
!endsub

!startsub collections
skinparam collections {
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
}
!endsub

!startsub control
skinparam control {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}
!endsub

!startsub entity
skinparam entity {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}
!endsub

!startsub boundary
skinparam boundary {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}
!endsub

!startsub agent
skinparam agent {
	BackgroundColor #orange
	BorderColor #999999
	FontColor #333333
}
!endsub

!startsub note
skinparam note {
	BorderThickness 1
	BackgroundColor $LIGHTSTEELBLUE_LIGHT-$LIGHTSTEELBLUE_DARK
	BorderColor $LIGHTSTEELBLUE_DARK
	FontColor $WHITE
}
!endsub

!startsub artifact
skinparam artifact {
	BackgroundColor $WHITE-$LIGHT
	BorderColor $GRAY
	FontColor $GRAY
}
!endsub

!startsub component
skinparam component {
	BackgroundColor  $BRONZE_LIGHT-$BRONZE_DARK
	BorderColor  $BRONZE_DARK
	FontColor $SUCCESS_TEXT
}
!endsub

!startsub interface
skinparam interface {
	BackgroundColor  $DANGER_LIGHT
	BorderColor  $DANGER
	FontColor $DARK
}
!endsub

!startsub storage
skinparam storage {
	BackgroundColor $WARNING_LIGHT-$WARNING_DARK
  	BorderColor $WARNING_DARK
	FontColor $WARNING_TEXT
}
!endsub

!startsub node
skinparam node {
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
}
!endsub

!startsub cloud
skinparam cloud {
	BackgroundColor white-lightskyblue
	BorderColor $BGCOLOR
	FontColor $DARK
}
!endsub

!startsub database
skinparam database {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}
!endsub

!startsub actor
skinparam actor {
	FontColor $DARK
}
!endsub

!startsub class
skinparam class {
	HeaderBackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
	FontColor $PRIMARY_TEXT
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $DARK
	AttributeFontSize 11
}
!endsub

!startsub object
skinparam object {
	FontColor $DARK
	BackgroundColor $ALUMINUM_LIGHT-$ALUMINUM_DARK
	BorderColor $ALUMINUM_DARK
	StereotypeFontColor $LIGHT
	BorderThickness 1
	AttributeFontColor $WHITE
	AttributeFontSize 11
}
!endsub

!startsub usecase
skinparam usecase {
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY
	BorderColor $SECONDARY
	BorderThickness 2
	FontColor $SECONDARY_TEXT
	StereotypeFontColor $PRIMARY
}
!endsub

!startsub rectangle
skinparam rectangle {
	BackgroundColor $WHITE-$LIGHT
	BorderColor $LIGHT
	BorderThickness 2
	FontColor $PRIMARY_TEXT
	StereotypeFontColor $PRIMARY
}
!endsub

!startsub package
skinparam package {
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY
  	BorderColor $PRIMARY
	FontColor $PRIMARY
	BorderThickness 2
}
!endsub

!startsub folder
skinparam folder {
	BackgroundColor $WHITE-$LIGHT
  	BorderColor $WARNING
	FontColor $WARNING
	BorderThickness 2
}
!endsub

!startsub frame
skinparam frame {
	BackgroundColor $PRIMARY-$PRIMARY_DARK
  	BorderColor $INFO
	FontColor $INFO
	BorderThickness 2
}
!endsub

!startsub state
skinparam state {
	StartColor $INFO
	EndColor $INFO
	BackgroundColor $LIGHTSTEELBLUE_LIGHT-$LIGHTSTEELBLUE_DARK
	BorderColor $LIGHTSTEELBLUE_DARK
	FontColor $INFO
	AttributeFontColor $SECONDARY
    AttributeFontSize 11
}
!endsub

!startsub queue
skinparam queue {
	BackgroundColor $WARNING-$WARNING_DARK
  	BorderColor $WARNING_DARK
	FontColor $WARNING_TEXT
}
!endsub

!startsub card
skinparam card {
	BackgroundColor $INFO_LIGHT-$INFO_DARK
	BorderColor $INFO
	FontColor $INFO_TEXT
}
!endsub

!startsub file
skinparam file {
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY_DARK
	BorderColor $GRAY
	FontColor $LIGHT

}
!endsub

!startsub stack
skinparam stack {
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
}
!endsub
