''
'' Cerulean theme based off of the bootstrap theme of the same name
'' https://bootswatch.com/cerulean/
''
'' Author: Brett Schwarz

''
'' Colors taken from the css file of the BS theme
''
!$BLUE = "#2A9FD6"
!$INDIGO = "#6610f2"
!$PURPLE = "#6f42c1"
!$PINK = "#e83e8c"
!$RED = "#CC0000"
!$ORANGE = "#fd7e14"
!$YELLOW = "#FF8800"
!$GREEN = "#77B300"
!$TEAL = "#20c997"
!$CYAN = "#9933CC"
!$WHITE = "#FFF"
!$GRAY_LIGHT = "#222"
!$GRAY = "#555"
!$PRIMARY = "#2A9FD6"
!$SECONDARY = "#555"
!$SUCCESS = "#77B300"
!$INFO = "#9933CC"
!$WARNING = "#FF8800"
!$DANGER = "#CC0000"
!$LIGHT = "#222"
!$DARK = "#ADAFAE"

'' *_DARK = tint (lighter) of the main color of 80%
''          where TINT is calculated by clr + (255-clr) * tint_factor
'' *_LIGHT = shade (darker) of the main color of 80%
''          and SHADE is calculated by clr * (1 - shade_factor)
''
!$PRIMARY_DARK = "#55B2DE"
!$PRIMARY_LIGHT = "#227FAB"
!$PRIMARY_TEXT = $WHITE
!$SECONDARY_DARK = "#777777"
!$SECONDARY_LIGHT = "#444444"
!$SECONDARY_TEXT = $WHITE
!$INFO_DARK = "#AD5CD6"
!$INFO_TEXT = $WHITE
!$SUCCESS_DARK = "#92C233"
!$SUCCESS_LIGHT = "#5F8F00"
!$SUCCESS_TEXT = $WHITE
!$WARNING_DARK = "#FFA033"
!$WARNING_TEXT = $WHITE
!$DANGER_DARK = "#D63333"
!$DANGER_TEXT = $WHITE
!$DARK_DARK = "#BDBFBE"
!$DARK_LIGHT = "#8A8C8B"
!$LIGHT_DARK = "#4E4E4E"
!$LIGHT_LIGHT = "#1B1B1B"

!function $success($msg)
  <font color=$SUCCESS><b>$msg
!endfunction

!function $failure($msg)
  <font color=$DANGER><b>$msg
!endfunction

!function $warning($msg)
  <font color=$WARNING><b>$msg
!endfunction

!$THEME = "cyborg"

''
'' Global Default Values
''
skinparam defaultFontName       "Helvetica"
skinparam defaultFontSize       12
'skinparam LegendBackgroundColor $LIGHT
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    10
skinparam BoxPadding            2
skinparam Padding               2
skinparam TitleFontColor	    $DARK
skinparam TitleFontSize	    	20
skinparam TitleBorderThickness 	0
'skinparam TitleBorderColor	 	transparent
'skinparam TitleBackgroundColor	transparent
skinparam ArrowColor            $DARK


skinparam legend {
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_DARK
	FontColor $DARK
}

skinparam activity {
	TitleFontSize 20
	TitleFontColor $DARK
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY
	BackgroundColor $PRIMARY
	BarColor $SUCCESS
	StartColor $INFO
	EndColor $INFO
	''
	DiamondBackgroundColor $SECONDARY_LIGHT
  	DiamondBorderColor $SECONDARY_DARK
  	DiamondFontColor $SECONDARY_TEXT
}
	
skinparam sequence {
	BorderColor $PRIMARY
	TitleFontSize 20
	TitleFontColor $DARK
	BackgroundColor transparent
	StartColor $PRIMARY
	EndColor $PRIMARY
	''
    ParticipantBackgroundColor $PRIMARY
    ParticipantBorderColor $PRIMARY
	ParticipantBorderThickness 0
	ParticipantFontColor $PRIMARY_TEXT
	''ParticipantFontStyle bold
	''
	ActorBackgroundColor transparent
    ActorBorderColor $PRIMARY
	ActorFontColor $PRIMARY
	''
	ArrowThickness 3
	ArrowColor $PRIMARY
	''
	BoxBackgroundColor transparent
	BoxBorderColor $DARK
	BoxFontColor $DARk
	''
	LifeLineBorderColor $SECONDARY
	LifeLineBorderThickness 0
	LifeLineBackgroundColor $SECONDARY_DARK
	''
	''GroupBorderStyle dashed
	GroupBorderColor $DARK
	GroupFontColor $DARK
	GroupHeaderFontColor $INFO
	''
	DividerBackgroundColor $DARK
    DividerBorderColor $DARK
    DividerBorderThickness 2
    DividerFontColor $LIGHT
	''
	ReferenceBorderColor $DARK
	ReferenceFontColor $DARK
	ReferenceHeaderFontColor $INFO
}

skinparam partition {
	BorderColor $PRIMARY
	FontColor $PRIMARY
	BackgroundColor transparent
}

skinparam collections {
	BackgroundColor $PRIMARY
	BorderColor $PRIMARY_DARK
}

skinparam control {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}

skinparam entity {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}

skinparam boundary {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}

skinparam agent {
	BackgroundColor $WARNINIG
	BorderColor $WARNING_LIGHT
	FontColor $DARK
}

skinparam note {
	BorderThickness 1
	BackgroundColor $INFO
	BorderColor $INFO_DARK
	FontColor $WHITE
}

skinparam artifact {
	BackgroundColor $DARK
	BorderColor $DARK_DARK
	FontColor $LIGHT
}

skinparam component {
	BackgroundColor  $SUCCESS
	BorderColor  $SUCCESS_DARK
	FontColor $SUCCESS_TEXT
}

skinparam interface {
	BackgroundColor  $DANGER_DARK
	BorderColor  $DANGER
	FontColor $DARK
}

skinparam storage {
	BackgroundColor $WARNING
  	BorderColor $WARNING_DARK
	FontColor $WARNING_TEXT
}

skinparam node {
	BackgroundColor  $SECONDARY
	BorderColor $DARK
	FontColor $DARK
}

skinparam cloud {
	BackgroundColor white-$PRIMARY_DARK
	BorderColor transparent
	FontColor $DARK
}

skinparam database {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
}

skinparam actor {
	FontColor $DARK
}

skinparam class {
	HeaderBackgroundColor $PRIMARY_LIGHT
	FontColor $PRIMARY_TEXT
	BackgroundColor $PRIMARY
	BorderColor $PRIMARY_DARK
	StereotypeFontColor $DARK
	LineThickness 4
	BorderThickness 1
	AttributeFontColor $LIGHT
}

skinparam object {
	FontColor $SUCCESS
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $DARK
}

skinparam usecase {
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY
	BorderThickness 2
	FontColor $SECONDARY_TEXT
	StereotypeFontColor $PRIMARY
}


skinparam rectangle {
	BackgroundColor $SECONDARY_LIGHT
	BorderColor $PRIMARY_LIGHT
	BorderThickness 2
	FontColor $PRIMARY
	StereotypeFontColor $PRIMARY
}

skinparam package {
	BackgroundColor $SECONDARY
  	BorderColor $PRIMARY
	FontColor $PRIMARY
	BorderThickness 2
}

skinparam folder {
	BackgroundColor $SECONDARY_LIGHT
  	BorderColor $WARNING
	FontColor $DARK
	BorderThickness 2
}

skinparam frame {
	BackgroundColor $SECONDARY_LIGHT
  	BorderColor $INFO
	FontColor $DARK
	BorderThickness 2
}

skinparam state {
  StartColor $INFO
  EndColor $INFO
  BackgroundColor $SECONDARY
  BorderColor $SECONDARY_DARK
  FontColor $SECONDARY_TEXT
}