''
'' Cerulean theme based off of the bootstrap theme of the same name
'' https://bootswatch.com/cerulean/
''
'' Author: Brett Schwarz

!$THEME = "cerulean"

''
'' Colors taken from the css file of the BS theme
''
!$BLUE = "#033C73"
!$INDIGO = "#6610F2"
!$PURPLE = "#6F42C1"
!$PINK = "#E83E8C"
!$RED = "#C71C22"
!$ORANGE = "#FD7E14"
!$YELLOW = "#DD5600"
!$GREEN = "#73A839"
!$TEAL = "#20C997"
!$CYAN = "#2FA4E7"
!$WHITE = "#FFF"
!$GRAY_DARK = "#343A40"
!$GRAY = "#868E96"
!$PRIMARY = "#2FA4E7"
!$SECONDARY = "#E9ECEF"
!$SUCCESS = "#73A839"
!$INFO = "#033C73"
!$WARNING = "#DD5600"
!$DANGER = "#C71C22"
!$LIGHT = "#F8F9FA"
!$DARK = "#343A40"

'' *_LIGHT = tint (lighter) of the main color of 80%
''          where TINT is calculated by clr + (255-clr) * tint_factor
'' *_DARK = shade (darker) of the main color of 80%
''          and SHADE is calculated by clr * (1 - shade_factor)
''
!$PRIMARY_LIGHT = "#59B6EC"
!$PRIMARY_DARK = "#2683B9"
!$PRIMARY_TEXT = $WHITE
!$SECONDARY_LIGHT = "#EDF0F2"
!$SECONDARY_DARK = "#BABDBF"
!$SECONDARY_TEXT = $DARK
!$INFO_LIGHT = "#35638F"
!$INFO_TEXT = $WHITE
!$SUCCESS_LIGHT = "#8FB961"
!$SUCCESS_TEXT = $WHITE
!$WARNING_LIGHT = "#E47833"
!$WARNING_TEXT = $WHITE
!$DANGER_LIGHT = "#D2494E"
!$DANGER_TEXT = $WHITE

!function $success($msg)
  <font color=$SUCCESS><b>$msg
!endfunction

!function $failure($msg)
  <font color=$DANGER><b>$msg
!endfunction

!function $warning($msg)
  <font color=$WARNING><b>$msg
!endfunction

''
'' Global Default Values
''
skinparam defaultFontName       "Verdana"
skinparam defaultFontSize       12
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    10
skinparam BoxPadding            2
skinparam Padding               2
skinparam TitleFontColor	    $DARK
skinparam TitleFontSize	    	20
skinparam TitleBorderThickness 	0
skinparam ArrowColor            $GRAY


skinparam legend {
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_DARK
	FontColor $DARK
}

skinparam activity {
	TitleFontSize 20
	TitleFontColor $DARK
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY
	BarColor $SUCCESS
	StartColor $INFO
	EndColor $INFO
	''
	DiamondBackgroundColor $WHITE-$SECONDARY_LIGHT
  	DiamondBorderColor $SECONDARY_DARK
	DiamondFontColor $SECONDARY_TEXT
}
	
skinparam sequence {
	BorderColor $PRIMARY
	TitleFontSize 20
	TitleFontColor $DARK
	BackgroundColor transparent
	StartColor $PRIMARY
	EndColor $PRIMARY
	''
    ParticipantBackgroundColor $PRIMARY_LIGHT-$PRIMARY
    ParticipantBorderColor $PRIMARY
	ParticipantBorderThickness 0
	ParticipantFontColor $PRIMARY_TEXT
	''
	ActorBackgroundColor transparent
    ActorBorderColor $PRIMARY
	ActorFontColor $PRIMARY
	''
	ArrowThickness 3
	ArrowColor $PRIMARY
	''
	BoxBackgroundColor $LIGHT
	BoxBorderColor $GRAY
	BoxFontColor $DARK
	''
	LifeLineBorderColor $SECONDARY
	LifeLineBorderThickness 0
	LifeLineBackgroundColor $SECONDARY_LIGHT
	''
	GroupBorderColor $GRAY
	GroupFontColor $DARK
	GroupHeaderFontColor $INFO
	''
	DividerBackgroundColor $WHITE-$LIGHT
    DividerBorderColor $GRAY
    DividerBorderThickness 2
    DividerFontColor $DARK
	''
	ReferenceBorderColor $GRAY
	ReferenceFontColor $DARK
	ReferenceHeaderFontColor $INFO
}

skinparam partition {
	BorderColor $PRIMARY
	FontColor $PRIMARY
	BackgroundColor transparent
}

skinparam collections {
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY
	BorderColor $PRIMARY
}

skinparam control {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}

skinparam entity {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}

skinparam boundary {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $DARK
}

skinparam agent {
	BackgroundColor #orange
	BorderColor #999999
	FontColor #333333
}

skinparam note {
	BorderThickness 1
	BackgroundColor $INFO_LIGHT-$INFO
	BorderColor $INFO
	FontColor $WHITE
}

skinparam artifact {
	BackgroundColor $WHITE-$LIGHT
	BorderColor $GRAY
	FontColor $DARK
}

skinparam component {
	BackgroundColor  $SUCCESS_LIGHT-$SUCCESS
	BorderColor  $SUCCESS
	FontColor $SUCCESS_TEXT
}

skinparam interface {
	BackgroundColor  $DANGER_LIGHT
	BorderColor  $DANGER
	FontColor $DARK
}

skinparam storage {
	BackgroundColor $WARNING_LIGHT-$WARNING
  	BorderColor $WARNING
	FontColor $WARNING_TEXT
}

skinparam node {
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY
	BorderColor $DARK
	FontColor $DARK
}

skinparam cloud {
	BackgroundColor white-lightskyblue
	BorderColor transparent
	FontColor $DARK
}

skinparam database {
	BackgroundColor  $PRIMARY_LIGHT-$PRIMARY
	BorderColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
}

skinparam actor {
	FontColor $DARK
}

skinparam class {
	HeaderBackgroundColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
	BackgroundColor $PRIMARY_LIGHT-$PRIMARY_DARK
	BorderColor $PRIMARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $DARK
	AttributeFontSize 11
}

skinparam object {
	FontColor $SUCCESS
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY_DARK
	BorderColor $SECONDARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $DARK
	AttributeFontSize 11
}

skinparam usecase {
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY
	BorderColor $SECONDARY
	BorderThickness 2
	FontColor $SECONDARY_TEXT
	StereotypeFontColor $PRIMARY
}


skinparam rectangle {
	BackgroundColor $SECONDARY_DARK
	BorderColor $PRIMARY_DARK
	BorderThickness 2
	FontColor $PRIMARY
	StereotypeFontColor $PRIMARY
}

skinparam package {
	BackgroundColor $SECONDARY_LIGHT-$SECONDARY
  	BorderColor $PRIMARY
	FontColor $PRIMARY
	BorderThickness 2
}

skinparam folder {
	BackgroundColor $WHITE-$SECONDARY_LIGHT
  	BorderColor $WARNING
	FontColor $DARK
	BorderThickness 2
}

skinparam frame {
	BackgroundColor $WHITE-$SECONDARY_LIGHT
  	BorderColor $INFO
	FontColor $DARK
	BorderThickness 2
}

skinparam state {
  StartColor $INFO
  EndColor $INFO
  BackgroundColor $SECONDARY
  BorderColor $SECONDARY_DARK
  FontColor $SECONDARY_TEXT
}