@startuml

!if %variable_exists("$THEME")
title $THEME
!else
title Component Diagram
!endif

skinparam BackgroundColor transparent

package "My Package" {
  HTTP - [First Component]
  [Another Component]
}
 
node "My Node" {
  FTP - [Second Component]
  [First Component] --> FTP
} 

cloud "My Cloud" {
  [Example 1]
}


database "My Database" {
  folder "My folder" {
	[Folder 3]
  }
  frame "My Frame" {
	[Frame 4]
  }
}

artifact "My Artifact"
storage "My Storage"

[Another Component] --> [Example 1]
[Example 1] --> [Folder 3]
[Folder 3] --> [Frame 4]

@enduml