@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/black-knight/puml-theme-black-knight.puml

|Actor_For_red|
start
if (color?) is (red) then
$DANGER:**action red**;
:foo1;
else (not red)
|Actor_For_no_red|
$SUCCESS:**action not red**;
:foo2;
endif
|Next_Actor|
$INFO:foo3;
:foo4;
|Final_Actor|
$WARNING:stop;
@enduml