@startuml

!if %variable_exists("$THEME")
title Swinlane Diagram - $THEME theme
!else
title Swinlane Diagram 
!endif

|Actor_For_red|
start
if (color?) is (red) then
:**action red**;
:foo1;
else (not red)
|Actor_For_no_red|
:**action not red**;
:foo2;
endif
|Next_Actor|
:foo3;
:foo4;
|Final_Actor|
:stop;
@enduml