@startuml

!if %variable_exists("$THEME")
title $THEME theme
!else
title Sequence Diagram
!endif

legend
This is my legend
endlegend

!if %variable_exists("$TITLE")
title $TITLE
!else
title Usecase Diagram
!endif

skinparam BackgroundColor transparent

left to right direction
actor customer
actor clerk
rectangle checkout {
  customer -- (checkout)
  (checkout) .> (payment) : include
  (help) .> (checkout) : extends
  (checkout) -- clerk
}
@enduml