@startwbs

!if %variable_exists("$THEME")
title Work Breakdown Diagram - $THEME theme
!else
title Work Breakdown Diagram
!endif

!$DIAGRAM = "wbs"

+ New Job
++ Decide on Job Requirements
+++ Identity gaps
+++ Review JDs
++++ Sign-Up for courses
++++ Volunteer
++++ Reading
++- Checklist
+++- Responsibilities
+++- Location
++ CV Upload Done
+++ CV Updated
++++ Spelling & Grammar
++++ Check dates
---- Skills
+++ Recruitment sites chosen
@endwbs