''
'' hacker theme based off of the Jekyll theme of the same name
'' https://github.com/pages-themes/hacker
''
'' Author: Brett Schwarz

!$THEME = "hacker"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

skinparam backgroundColor $BGCOLOR

''
'' Colors taken from the _default_colors.scss file
''
!$PRIMARY = "#b5e853"
!$PRIMARY_LIGHT = "#d3f198"
!$PRIMARY_TEXT = "#151515"
!$SECONDARY = "#6a9fb5"
!$SECONDARY_LIGHT = "#a6c5d3"
!$SECONDARY_TEXT = "#fefefe"
!$SUCCESS = "#90a959"
!$SUCCESS_LIGHT = "#bccb9b"
!$INFO = "#aa759f"
!$INFO_LIGHT = "#ccacc5"
!$WARNING = "#f4bf75"
!$WARNING_LIGHT = "#f8d9ac"
!$DANGER = "#ac4142"
!$DANGER_LIGHT = "#cd8d8e"
!$LIGHT = "#151515"
!$DARK = "#eaeaea"

!function $success($msg)
  <font color=$SUCCESS><b>$msg
!endfunction

!function $failure($msg)
  <font color=$DANGER><b>$msg
!endfunction

!function $warning($msg)
  <font color=$WARNING><b>$msg
!endfunction

skinparam  {
    defaultFontName   "Verdana"
    defaultFontSize   12
    defaultTextAlignment center
    shadowing false
    RoundCorner 10
    TitleFontSize 18
    TitleFontColor $PRIMARY_TEXT
}

''
'' Global Default Values
''
skinparam defaultFontName       "Verdana"
skinparam defaultFontSize       12
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    40
skinparam BoxPadding            40
skinparam Padding               5
skinparam ArrowColor            $DARK
skinparam stereotype {
    CBackgroundColor $SECONDARY_DARK
    CBorderColor $SECONDARY_LIGHT
    ABackgroundColor $SUCCESS_LIGHT
    ABorderColor $SUCCESS_DARK
    IBackgroundColor $DANGER_LIGHT
    IBorderColor $DANGER_DARK
    EBackgroundColor $WARNING_LIGHT
    EBorderColor $WARNING_DARK
    NBackgroundColor $INFO_LIGHT
    NBorderColor $INFO_DARK
}
skinparam title {
	FontColor	                 $PRIMARY
	BorderColor	                 $PRIMARY
	FontSize	    	         20
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              $LIGHT-black
}


skinparam legend {
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_DARK
	FontColor $DARK
}

!startsub activity
skinparam activity {
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY_LIGHT
	BackgroundColor $PRIMARY
	BarColor $SUCCESS
	StartColor $INFO
	EndColor $INFO
	''
	DiamondBackgroundColor $SECONDARY
  	DiamondBorderColor $SECONDARY_LIGHT
  	DiamondFontColor $SECONDARY_TEXT
}
!endsub

!startsub sequence
skinparam sequence {
	BorderColor $PRIMARY
	' For some reason sequence title font color does not pick up from global
	TitleFontColor $PRIMARY
	BackgroundColor $BGCOLOR
	StartColor $PRIMARY
	EndColor $PRIMARY
	''
    ParticipantBackgroundColor $PRIMARY
    ParticipantBorderColor $PRIMARY_LIGHT
	ParticipantBorderThickness 2
	ParticipantFontColor $PRIMARY_TEXT
	''
	ActorBackgroundColor $BGCOLOR
    ActorBorderColor $PRIMARY
	ActorFontColor $PRIMARY
	''
	ArrowThickness 3
	ArrowColor $PRIMARY
	ArrowFontColor $FGCOLOR
	''
	BoxBackgroundColor $BGCOLOR
	BoxBorderColor $DARK
	BoxFontColor $DARk
	''
	LifeLineBorderColor $SECONDARY
	LifeLineBorderThickness 2
	LifeLineBackgroundColor $SECONDARY_DARK
	''
	GroupBorderColor $DARK
	GroupFontColor $DARK
	GroupHeaderFontColor $INFO
	''
	DividerBackgroundColor $DARK
    DividerBorderColor $DARK
    DividerBorderThickness 2
    DividerFontColor $LIGHT
	''
	ReferenceBackgroundColor $BGCOLOR
	ReferenceBorderColor $DARK
	ReferenceFontColor $LIGHT
	ReferenceHeaderFontColor $INFO
}
!endsub

!startsub partition
skinparam partition {
	BorderColor $PRIMARY
	FontColor $PRIMARY
	BackgroundColor $BGCOLOR
}
!endsub

!startsub collections
skinparam collections {
	BackgroundColor $PRIMARY
	BorderColor $PRIMARY_LIGHT
}
!endsub

!startsub control
skinparam control {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_LIGHT
	FontColor $DARK
}
!endsub

!startsub entity
skinparam entity {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_LIGHT
	FontColor $DARK
}
!endsub

!startsub boundary
skinparam boundary {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_LIGHT
	FontColor $DARK
}
!endsub

!startsub agent
skinparam agent {
	BackgroundColor $WARNING
	BorderColor $WARNING_LIGHT
	FontColor $DARK
}
!endsub

!startsub note
skinparam note {
	BorderThickness 1
	BackgroundColor $INFO
	BorderColor $INFO_DARK
	FontColor $WHITE
}
!endsub

!startsub artifact
skinparam artifact {
	BackgroundColor $DARK
	BorderColor $DARK_DARK
	FontColor $LIGHT
}
!endsub

!startsub component
skinparam component {
	BackgroundColor  $SUCCESS
	BorderColor  $SUCCESS_LIGHT
	FontColor $SUCCESS_TEXT
}
!endsub

!startsub interface
skinparam interface {
	BackgroundColor  $DANGER
	BorderColor  $DANGER_LIGHT
	FontColor $DARK
}
!endsub

!startsub storage
skinparam storage {
	BackgroundColor $WARNING
  	BorderColor $WARNING_LIGHT
	FontColor $WARNING_TEXT
}
!endsub

!startsub node
skinparam node {
	BackgroundColor  $SECONDARY
	BorderColor $SECONDARY_LIGHT
	FontColor $DARK
}
!endsub

!startsub cloud
skinparam cloud {
	BackgroundColor white-#F2FCFE
	BorderColor white
	FontColor $LIGHT
}
!endsub

!startsub database
skinparam database {
	BackgroundColor  $PRIMARY
	BorderColor $PRIMARY_LIGHT
	FontColor $DARK
}
!endsub

!startsub actor
skinparam actor {
	FontColor $DARK
}
!endsub

!startsub class
skinparam class {
	HeaderBackgroundColor $PRIMARY_LIGHT
	FontColor $PRIMARY_TEXT
	BackgroundColor $PRIMARY
	BorderColor $PRIMARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $LIGHT
	AttributeFontSize 11
}
!endsub

!startsub object
skinparam object {
	FontColor $SUCCESS
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_DARK
	StereotypeFontColor $DARK
	BorderThickness 1
	AttributeFontColor $SECONDARY_TEXT
	AttributeFontSize 11
}
!endsub

!startsub usecase
skinparam usecase {
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY
	BorderThickness 2
	FontColor $SECONDARY_TEXT
	StereotypeFontColor $PRIMARY
}
!endsub

!startsub rectangle
skinparam rectangle {
	BackgroundColor $SECONDARY_LIGHT
	BorderColor $PRIMARY_LIGHT
	BorderThickness 2
	FontColor $PRIMARY
	StereotypeFontColor $PRIMARY
}
!endsub

!startsub package
skinparam package {
	'BackgroundColor $BGCOLOR
  	BorderColor $PRIMARY
	FontColor $PRIMARY
	BorderThickness 2
}
!endsub

!startsub folder
skinparam folder {
	BackgroundColor $SECONDARY_LIGHT
  	BorderColor $WARNING
	FontColor $WARNING
	BorderThickness 2
}
!endsub

!startsub frame
skinparam frame {
	BackgroundColor $SECONDARY_LIGHT
  	BorderColor $INFO
	FontColor $INFO
	BorderThickness 2
}
!endsub

!startsub state
skinparam state {
	StartColor $INFO
	EndColor $INFO
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_LIGHT
	FontColor $SECONDARY_TEXT
	AttributeFontColor $SECONDARY_TEXT
	AttributeFontSize 11
}
!endsub

!startsub queue
skinparam queue {
	BackgroundColor $WARNING
  	BorderColor $WARNING_LIGHT
	FontColor $WARNING_TEXT
}
!endsub

!startsub card
skinparam card {
	BackgroundColor $INFO
	BorderColor $INFO_LIGHT
	FontColor $INFO_TEXT
}
!endsub

!startsub file
skinparam file {
	BackgroundColor $SECONDARY
	BorderColor $SECONDARY_LIGHT
	FontColor $DARK
}
!endsub

!startsub stack
skinparam stack {
	BackgroundColor $PRIMARY
	BorderColor $PRIMARY_LIGHT
	FontColor $PRIMARY_TEXT
}
!endsub


<style>
wbsDiagram {
    LineColor $PRIMARY
    BorderThickness 3
    BackgroundColor $LIGHT
    FontColor $PRIMARY
    :depth(0) {
        fontSize 16
        fontStyle bold
        fontColor $SECONDARY
    }
    :depth(1) {
        fontSize 14
        padding 5
        fontStyle bold
    }
    :depth(2) {
        fontSize 12
        padding 4
    }
    :depth(3) {
        fontSize 11
        padding 3
        fontColor $INFO
    }

}
</style>

<style>
mindmapDiagram {
    LineColor $PRIMARY
    BorderThickness 3
    BackgroundColor $LIGHT
    FontColor $PRIMARY
    :depth(0) {
        fontSize 16
        fontStyle bold
        fontColor $SECONDARY
    }
    :depth(1) {
        fontSize 14
        padding 5
        fontStyle bold
    }
    :depth(2) {
        fontSize 12
        padding 4
    }
    :depth(3) {
        fontSize 11
        padding 3
        fontColor $INFO
    }

}
</style>
