''
'' hacker theme based off of the Jekyll theme of the same name
'' https://github.com/pages-themes/hacker
''
'' Author: Brett Schwarz

!$THEME = "hacker"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

skinparam backgroundColor $BGCOLOR

''
'' Colors taken from the _default_colors.scss file
''
!$apple-blossom = #ac4142;
!$alto = #d0d0d0;
!$bouquet = #aa759f;
!$chelsea-cucumber = #90a959;
!$cod-grey = #151515;
!$conifer = #b5e853;
!$dove-grey = #666;
!$gallery = #eaeaea;
!$grey = #888;
!$gulf-stream = #75b5aa;
!$hippie-blue = #6a9fb5;
!$potters-clay = #8f5536;
!$rajah = #f4bf75;
!$raw-sienna = #d28445;
!$silver-chalice = #aaa;

!$SUCCESS = $chelsea-cucumber
!$DANGER = $apple-blossom
!$WARNING = $rajah

!function $success($msg)
  <font color=$SUCCESS><b>$msg
!endfunction

!function $failure($msg)
  <font color=$DANGER><b>$msg
!endfunction

!function $warning($msg)
  <font color=$WARNING><b>$msg
!endfunction

skinparam  {
    defaultFontName   "Verdana"
    defaultFontSize   12
    defaultTextAlignment center
    shadowing false
    RoundCorner 10
    TitleFontSize 18
    TitleFontColor $gallery
}
<style>
wbsDiagram {
    LineColor $conifer
    BorderThickness 3
    BackgroundColor $cod-grey
    FontColor $gallery
    :depth(0) {
        fontSize 16
        fontStyle bold
        fontColor $hippie-blue
    }
    :depth(1) {
        fontSize 14
        padding 5
        fontStyle bold
    }
    :depth(2) {
        fontSize 12
        padding 3
    }
    :depth(3) {
        fontSize 10
        padding 2
    }

}
</style>