''
'' Cerulean theme based off of the bootstrap theme of the same name
'' https://bootswatch.com/cerulean/
''

''
'' Colors taken from the css file of the BS theme
''
!$BLUE = "#033C73"
!$INDIGO = "#6610F2"
!$PURPLE = "#6F42C1"
!$PINK = "#E83E8C"
!$RED = "#C71C22"
!$ORANGE = "#FD7E14"
!$YELLOW = "#DD5600"
!$GREEN = "#73A839"
!$TEAL = "#20C997"
!$CYAN = "#2FA4E7"
!$WHITE = "#FFF"
!$GRAY_DARK = "#343A40"
!$GRAY = "#868E96"
!$PRIMARY = "#2FA4E7"
!$SECONDARY = "#E9ECEF"
!$SUCCESS = "#73A839"
!$INFO = "#033C73"
!$WARNING = "#DD5600"
!$DANGER = "#C71C22"
!$LIGHT = "#F8F9FA"
!$DARK = "#343A40"

'' *_TINT = tint (lighter) of the main color of 80%
''          where TINT is calculated by clr + (255-clr) * tint_factor
'' *_SHADE = shade (darker) of the main color of 80%
''          and SHADE is calculated by clr * (1 - shade_factor)
''
!$PRIMARY_TINT = "#59B6EC"
!$PRIMARY_SHADE = "#2683B9"
!$PRIMARY_TEXT = $WHITE
!$SECONDARY_TINT = "#EDF0F2"
!$SECONDARY_SHADE = "#BABDBF"
!$SECONDARY_TEXT = $DARK
!$INFO_TINT = "#35638F"
!$INFO_TEXT = $WHITE
!$SUCCESS_TINT = "#8FB961"
!$SUCCESS_TEXT = $WHITE
!$WARNING_TINT = "#E47833"
!$WARNING_TEXT = $WHITE
!$DANGER_TINT = "#D2494E"
!$DANGER_TEXT = $WHITE

!function $success($msg)
  <font color=$SUCCESS><b>$msg
!endfunction

!function $failure($msg)
  <font color=$DANGER><b>$msg
!endfunction

!function $warning($msg)
  <font color=$WARNING><b>$msg
!endfunction


''
'' Global Default Values
''
skinparam defaultFontName       "Arial"
skinparam defaultFontSize       12
skinparam LegendBackgroundColor $LIGHT
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    10
skinparam BoxPadding            2
skinparam Padding               2
skinparam TitleFontColor	    red

skinparam activity {
	TitleFontSize 14
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY
	BackgroundColor $PRIMARY_TINT-$PRIMARY
	BarColor $GRAY
	StartColor $INFO
	EndColor $INFO
	''
	DiamondBackgroundColor $WHITE-$SECONDARY_TINT
  	DiamondBorderColor $SECONDARY
}
	
skinparam sequence {
	BorderColor $PRIMARY
	TitleFontSize 14
	TitleFontColor $DARK
	BackgroundColor transparent
	StartColor $PRIMARY
	EndColor $PRIMARY
	''
    ParticipantBackgroundColor $PRIMARY_TINT-$PRIMARY
    ParticipantBorderColor $PRIMARY
	ParticipantBorderThickness 0
	ParticipantFontColor $PRIMARY_TEXT
	''ParticipantFontStyle bold
	''
	ActorBackgroundColor transparent
    ActorBorderColor $PRIMARY
	ActorFontColor $PRIMARY
	''
	ArrowColor $LIGHT
	ArrowThickness 4
	''
	BoxBackgroundColor $LIGHT
	BoxBorderColor $GRAY
	BoxFontColor $DARk
	''
	LifeLineBorderColor $SECONDARY
	LifeLineBorderThickness 4
	LifeLineBackgroundColor $SECONDARY_TINT
	''
	''GroupBorderStyle dashed
	GroupBorderColor #959595
	GroupFontColor #666666
	GroupHeaderFontColor #666666
	GroupHeaderFontSize 11
	''
	DividerBackgroundColor $WHITE-$LIGHT
    DividerBorderColor $GRAY
    DividerBorderThickness 2
    DividerFontColor $DARK
	''
	ReferenceBorderColor #959595
	ReferenceFontColor #666666
	ReferenceHeaderFontColor #666666
	ReferenceHeaderFontSize 11
}

skinparam partition {
  BorderColor #959595
  FontColor #959595
	BackgroundColor white
	ArrowColor #959595
	'ArrowColor #bbbbbb
	GroupTitleBackgroundColor #959595
	'LifeLineBorderColor #959595
	LifeLineBorderColor #bbbbbb
	GroupBorderColor #959595
	'GroupBorderStyle dashed
	GroupFontColor #666666
	GroupTitleFontColor #666666
}

skinparam collections {
	BackgroundColor $PRIMARY_TINT-$PRIMARY
	BorderColor $PRIMARY
}

skinparam control {
	BackgroundColor  $PRIMARY_TINT-$PRIMARY
	BorderColor $PRIMARY_SHADE
	FontColor $DARK
}

skinparam entity {
	BackgroundColor  $PRIMARY_TINT-$PRIMARY
	BorderColor $PRIMARY_SHADE
	FontColor $DARK
}

skinparam boundary {
	BackgroundColor  $PRIMARY_TINT-$PRIMARY
	BorderColor $PRIMARY_SHADE
	FontColor $DARK
}

skinparam agent {
	BackgroundColor #orange
	BorderColor #999999
	FontColor #333333
}

skinparam note {
	BorderThickness 1
	BackgroundColor $INFO_TINT-$INFO
	BorderColor $INFO
	FontColor $WHITE
}

skinparam artifact {
	BackgroundColor $WHITE-$LIGHT
	BorderColor $GRAY
	FontColor $DARK
}

skinparam component {
	BackgroundColor  $SUCCESS_TINT-$SUCCESS
	BorderColor  $SUCCESS
	FontColor $SUCCESS_TEXT
}

skinparam interface {
	BackgroundColor  $DANGER_TINT
	BorderColor  $DANGER
	FontColor $DARK
}

skinparam storage {
	BackgroundColor $WARNING_TINT-$WARNING
  	BorderColor $WARNING
	FontColor $WARNING_TEXT
}

skinparam node {
	BackgroundColor  #f2f3f4-#e5e7e9
	BorderColor #e5e7e9
	FontColor #333333
}

skinparam cloud {
	BackgroundColor white-$PRIMARY_TINT
	BorderColor $LIGHT
	FontColor $DARK
}

skinparam database {
	BackgroundColor  $PRIMARY_TINT-$PRIMARY
	BorderColor $PRIMARY_SHADE
	FontColor $DARK
}

skinparam actor {
	FontColor $DARK
}

skinparam class {
	FontColor $PRIMARY
	BackgroundColor $WHITE-$SECONDARY_TINT
	BorderColor $SECONDARY
	ArrowColor $SECONDARY_SHADE
	ArrowThickness 2
	StereotypeFontColor $DARK
	LineThickness 4
	BorderThickness 1
	AttributeFontColor $DARK
}

skinparam usecase {
	BackgroundColor $SECONDARY_TINT-$SECONDARY
	BorderColor $SECONDARY
	BorderThickness 2
	FontColor $DARK
	StereotypeFontColor $PRIMARY
}


skinparam rectangle {
	BackgroundColor $LIGHT
	BorderColor $PRIMARY_SHADE
	BorderThickness 2
}

skinparam package {
	BackgroundColor $WHITE-$SECONDARY_TINT
  	BorderColor $PRIMARY
	FontColor $PRIMARY
	BorderThickness 2
}

skinparam folder {
	BackgroundColor $WHITE-$SECONDARY_TINT
  	BorderColor $SECONDARY_SHADE
	FontColor $DARK
	BorderThickness 2
}

skinparam frame {
	BackgroundColor $WHITE-$SECONDARY
  	BorderColor $SECONDARY_SHADE
	FontColor $DARK
	BorderThickness 2
}